In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
import os

os.chdir('C:\\Users\justu\\Desktop\\Masterarbeit\\Data\\CE')
os.getcwd()
check = pd.read_csv('fs08.csv')

'C:\\Users\\justu\\Desktop\\Masterarbeit\\Data\\CE'

In [79]:
print('the number of variables is:')
print(len(list(check)))
print('number of observation per given variable:')
print(check.count())
column_types = list(check.dtypes)
column_names = list(check)

num = check.select_dtypes(exclude=['object'])
num_column_names = list(num)
arraynum = np.array(num)
perc = np.zeros(len(arraynum[0,:]))

for i in range(len(arraynum[0,:])):
    #print('10 percentile of', num_column_names[i])
    #print(np.percentile(arraynum[:,i],10))
    perc[i] = np.percentile(arraynum[:,i],10)
    
#
perc_names = pd.DataFrame(list(zip(num_column_names, list(perc))))
#perc_names = pd.DataFrame([num_column_names,perc])
perc_names
np.array(check.loc[:,'SND'])
#num.head()
#arraycheck = np.array(check)
#for i in range(len(arraycheck[0,:])):
#    print(np.mean(arraycheck[:,i]))
##['CUTENURE' + f'_{j}' for j in list(range(1,6)) if j!=3]

the number of variables is:
121
number of observation per given variable:
CustID            25989
QINTRVYR          25989
QINTRVMO          25989
NEWID             25989
AGE_REF           25989
AGE2              14503
CKBKACTX           3234
CKBK_CTX          25989
CUTENURE          25989
FAM_SIZE          25989
FINCBTAX          25989
MARITAL1          25989
PERSLT18          25989
RESPSTAT          25989
SAVACCTX           3240
SAVA_CTX          25989
SECESTX             601
SECESTX_          25989
ST_HOUS           25989
FDHOMEPQ          25989
FDHOMECQ          25989
FDAWAYPQ          25989
FDAWAYCQ          25989
ALCBEVPQ          25989
ALCBEVCQ          25989
SHELTPQ           25989
SHELTCQ           25989
UTILPQ            25989
UTILCQ            25989
HOUSOPPQ          25989
                  ...
rbtmo_2            4889
diff_2             4889
rbtamt             4339
rbtamt_chk         2545
rbtamt_e           1764
intrvyr_max       25989
intrvmo_max       25989
age               25989
adults            25989
timetrend         25989
int_entries       25989
last_timetrend    17769
chg_timetrend     17769
last_FD           17769
chg_FD            17769
last_SND          17769
chg_SND           17769
last_ND           17769
chg_ND            17769
last_DUR          17769
chg_DUR           17769
totalint          25989
timeleft          11941
time              11942
newmrrt_median    11941
nmorg             11942
qescrowx_sum      11942
qblncm1x_sum      11942
orgmrtx_sum       11942
morgpayment       11941
Length: 121, dtype: int64

array([1270.    , 1828.9999, 1343.    , ..., 5379.7499, 7150.9999,
       9876.    ])

Select data types that are not objects

In [42]:

#c_types_names[0][0]
#check.loc[:,c_names_spec].describe()

,CustID,QINTRVYR,QINTRVMO,NEWID,AGE_REF,AGE2,CKBKACTX,CUTENURE,FAM_SIZE,FINCBTAX,...,chg_DUR,totalint,timeleft,time,newmrrt_median,nmorg,qescrowx_sum,qblncm1x_sum,orgmrtx_sum,morgpayment
count,25989.000000,25989.000000,25989.000000,2.598900e+04,25989.000000,14503.000000,3234.000000,25989.000000,25989.000000,2.598900e+04,...,17769.000000,25989.000000,11941.000000,11942.000000,11941.000000,11942.000000,11942.000000,1.194200e+04,1.194200e+04,11941.000000
mean,190883.428450,2008.078379,6.686213,1.908838e+06,49.917542,49.890299,6991.392703,2.131863,2.588595,5.598908e+04,...,-155.035300,3.393936,19.257509,7.234282,0.067216,1.185396,326.641350,1.415966e+05,1.723937e+05,43.907407
std,3329.451236,0.488018,3.634644,3.329430e+04,15.558390,14.390290,30062.089895,1.291051,1.486242,6.389191e+04,...,6212.913389,0.791697,9.071128,6.058070,0.015648,0.486096,409.898132,1.397303e+05,1.532108e+05,93.795941
min,183843.000000,2007.000000,1.000000,1.838432e+06,18.000000,16.000000,0.000000,1.000000,1.000000,-1.048540e+05,...,-127751.642400,2.000000,-22.916667,0.000000,0.040000,1.000000,0.000000,0.000000e+00,5.350000e+02,-5182.925000
25%,188264.000000,2008.000000,3.000000,1.882644e+06,38.000000,39.000000,20.000000,1.000000,1.000000,1.424900e+04,...,-848.000000,3.000000,12.000000,2.666667,0.057500,1.000000,35.000000,5.392075e+04,7.800000e+04,20.334865
50%,190837.000000,2008.000000,7.000000,1.908374e+06,49.000000,49.000000,700.000000,2.000000,2.000000,3.854900e+04,...,0.000000,4.000000,21.833333,5.625000,0.063000,1.000000,223.000000,1.034515e+05,1.300000e+05,31.412030
75%,193477.000000,2008.000000,10.000000,1.934772e+06,61.000000,60.000000,2738.250000,4.000000,4.000000,7.616000e+04,...,771.000100,4.000000,27.000000,10.250000,0.075300,1.000000,441.000000,1.798815e+05,2.086290e+05,50.305405
max,197327.000000,2009.000000,12.000000,1.973273e+06,87.000000,87.000000,198845.000000,5.000000,14.000000,1.107217e+06,...,90754.000100,4.000000,43.583333,47.000000,0.190000,9.000000,6220.000000,1.444522e+06,1.644723e+06,5182.925000

Select data types where we have observations above a certain threshold

In [81]:
column_count = list(check.count())
c_count_names = list(zip(column_count,column_names))
c_count_names_spec = [i for i in c_count_names if i[0] > 20000]
print('variables where the number of observations is larger than 20000')
c_names_spec = [i[1] for i in c_count_names_spec]
print(c_names_spec)
checkdes = check.loc[:,c_names_spec].describe()
checkdes.index[:]
checkdes.loc['25%',:]

variables where the number of observations is larger than 20000
['CustID', 'QINTRVYR', 'QINTRVMO', 'NEWID', 'AGE_REF', 'CKBK_CTX', 'CUTENURE', 'FAM_SIZE', 'FINCBTAX', 'MARITAL1', 'PERSLT18', 'RESPSTAT', 'SAVA_CTX', 'SECESTX_', 'ST_HOUS', 'FDHOMEPQ', 'FDHOMECQ', 'FDAWAYPQ', 'FDAWAYCQ', 'ALCBEVPQ', 'ALCBEVCQ', 'SHELTPQ', 'SHELTCQ', 'UTILPQ', 'UTILCQ', 'HOUSOPPQ', 'HOUSOPCQ', 'HOUSEQPQ', 'HOUSEQCQ', 'APPARPQ', 'APPARCQ', 'CARTKNPQ', 'CARTKNCQ', 'OTHVEHPQ', 'OTHVEHCQ', 'GASMOPQ', 'GASMOCQ', 'VEHFINPQ', 'VEHFINCQ', 'MAINRPPQ', 'MAINRPCQ', 'VEHINSPQ', 'VEHINSCQ', 'VRNTLOPQ', 'VRNTLOCQ', 'PUBTRAPQ', 'PUBTRACQ', 'HEALTHPQ', 'HEALTHCQ', 'ENTERTPQ', 'ENTERTCQ', 'PERSCAPQ', 'PERSCACQ', 'READPQ', 'READCQ', 'EDUCAPQ', 'EDUCACQ', 'TOBACCPQ', 'TOBACCCQ', 'MISCPQ', 'MISCCQ', 'FINCBTXM', 'FSALARYM', 'Year', 'Quarter', 'FD', 'SND', 'ND', 'DUR', 'valid_finassets', 'intrvyr_max', 'intrvmo_max', 'age', 'adults', 'timetrend', 'int_entries', 'totalint']

CustID             1.882640e+05
QINTRVYR           2.008000e+03
QINTRVMO           3.000000e+00
NEWID              1.882644e+06
AGE_REF            3.800000e+01
CUTENURE           1.000000e+00
FAM_SIZE           1.000000e+00
FINCBTAX           1.424900e+04
MARITAL1           1.000000e+00
PERSLT18           0.000000e+00
RESPSTAT           1.000000e+00
ST_HOUS            2.000000e+00
FDHOMEPQ           3.543333e+02
FDHOMECQ           0.000000e+00
FDAWAYPQ           6.500010e+01
FDAWAYCQ           0.000000e+00
ALCBEVPQ           0.000000e+00
ALCBEVCQ           0.000000e+00
SHELTPQ            5.000000e+02
SHELTCQ            0.000000e+00
UTILPQ             2.783333e+02
UTILCQ             0.000000e+00
HOUSOPPQ           0.000000e+00
HOUSOPCQ           0.000000e+00
HOUSEQPQ           0.000000e+00
HOUSEQCQ           0.000000e+00
APPARPQ            0.000000e+00
APPARCQ            0.000000e+00
CARTKNPQ           0.000000e+00
CARTKNCQ           0.000000e+00
                       ...
PUBTRACQ           0.000000e+00
HEALTHPQ           2.500000e+01
HEALTHCQ           0.000000e+00
ENTERTPQ           7.700000e+01
ENTERTCQ           0.000000e+00
PERSCAPQ           0.000000e+00
PERSCACQ           0.000000e+00
READPQ             0.000000e+00
READCQ             0.000000e+00
EDUCAPQ            0.000000e+00
EDUCACQ            0.000000e+00
TOBACCPQ           0.000000e+00
TOBACCCQ           0.000000e+00
MISCPQ             0.000000e+00
MISCCQ             0.000000e+00
FINCBTXM           2.590000e+04
FSALARYM           8.000000e+03
Year               2.008000e+03
FD                 1.091000e+03
SND                2.542000e+03
ND                 3.109300e+03
DUR                1.878000e+03
valid_finassets    0.000000e+00
intrvyr_max        2.008000e+03
intrvmo_max        2.000000e+00
age                3.800000e+01
adults             1.000000e+00
timetrend          4.000000e+00
int_entries        1.000000e+00
totalint           3.000000e+00
Name: 25%, Length: 73, dtype: float64